#################
## KEYBINDINGS ##
#################

# https://wiki.hyprland.org/Configuring/Keywords/
$mainMod = SUPER # Super as main mod
#$ipc = ipc call you make in quickshell (check novtalia-shell for example)

# https://wiki.hyprlandd.org/Configuring/Binds/
bind = , F12, exec, $terminal
bind = ALT, F4, killactive,
bind = $mainMod, E, exec, $filemanager
bind = $mainMod, F, togglefloating,
bind = $mainMod, P, pseudo,
bind = $mainMod, O, layoutmsg, togglesplit,

# Window focus/split
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, J, movewindow, d
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod, H, movefocus, l
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d
bind = $mainMod, L, movefocus, r

# Workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 10, workspace, 10

# Active window to workspace
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHFIT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 10, movetoworkspace, 10

# Example special workspace (scratchpad) [Look up don't know what this is]
#bind = $mainMod, S, togglespecialworkspace, magic
#bind = $mainMod SHFIT, S, movetoworkspace, special:magic

# Scroll through workspaces
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mouse l&r
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

#Multimedia keys vol/brightness
#bindel = ,XF86AudioRaiseVolume, exec, $ipc volume increase
#bindel = ,XF86AudioLowerVolume, exec, $ipc volume decrease
#bindel = ,XF86AudioMute, exec, $ipc volume muteOutput
#bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
#bindel = ,XF86MonBrightnessUp, exec, $ipc brightness increase
#bindel = ,XF86MonBrightnessDown, exec, $ipc brightness decrease

# Requires playerctl
#bindl = , XF86AudioNext, exec, playerctl next
#bindl = , XF86AudioPause, exec, playerctl play-pause
#bindl = , XF86AudioPlay, exec, playerctl play-pause
#bindl = , XF86AudioPrev, exec, playerctl previous

#Quickshell core binds
#bind = ALT, SPACE, exec, $ipc launcher toggle
#bind = $mainMod, S, exec, $ipc controlCenter toggle
#bind = $mainMod, comma, exec, $ipc settings toggle

