source = ./monitors.conf
source = ./programs.conf
source = ./autostart.conf
source = ./envs.conf
source = ./look&feel.conf
source = ./keybinds.conf
source = ./windows&workspaces.conf
source = ./input.conf
