source = ./hypr-conf/monitors.conf
source = ./hypr-conf/programs.conf
source = ./hypr-conf/autostart.conf
source = ./hypr-conf/envs.conf
source = ./hypr-conf/look&feel.conf
source = ./hypr-conf/keybinds.conf
source = ./hypr-conf/windows&workspaces.conf
source = ./hypr-conf/input.conf
